# Generated by Django 4.1.7 on 2023-04-14 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendees',
            old_name='event',
            new_name='held_event',
        ),
        migrations.RenameField(
            model_name='publishedevent',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='registeredevent',
            old_name='event',
            new_name='published_event',
        ),
        migrations.RemoveField(
            model_name='heldevent',
            name='event',
        ),
        migrations.AddField(
            model_name='heldevent',
            name='published_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.publishedevent'),
            preserve_default=False,
        ),
    ]
