# Generated by Django 4.1.7 on 2023-04-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_options_alter_publishedevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='event',
            name='semester',
            field=models.CharField(default='Acad Year 2022 - 2023 Spring', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(choices=[('SE CLUB', 'SE CLUB'), ('FC CLUB', 'FC CLUB'), ('C ARCH CLUB', 'C ARCH CLUB'), ('CE CLUB', 'CIVIL ENGINEERING CLUB'), ('MEDIA CLUB', 'MEDIA CLUB'), ('AI CLUB', 'AI CLUB'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=50),
        ),
    ]
