# Generated by Django 4.2 on 2023-04-16 15:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_rename_event_attendees_held_event_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registeredevent',
            unique_together={('user', 'published_event')},
        ),
    ]
