# Generated by Django 4.2 on 2023-04-17 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_registeredevent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredevent',
            name='date_of_registration',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
