# Generated by Django 4.1.7 on 2023-04-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_options_event_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(choices=[('SE', 'SE CLUB'), ('FC', 'FC CLUB'), ('CARCH', 'C ARCH CLUB'), ('CE', 'CIVIL ENGINEERING CLUB'), ('MEDIA', 'MEDIA CLUB'), ('AI', 'AI CLUB'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=50),
        ),
    ]
