# Generated by Django 4.2 on 2023-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_registeredevent_date_of_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedevent',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
