# Generated by Django 4.2 on 2023-04-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_publishedevent_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heldevent',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=1, null=True),
        ),
    ]
