# Generated by Django 4.2 on 2023-04-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_heldevent_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heldevent',
            name='average_rating',
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(choices=[('SE CLUB', 'SE CLUB'), ('FC CLUB', 'FC CLUB'), ('CARCH CLUB', 'C ARCH CLUB'), ('CE CLUB', 'CIVIL ENGINEERING CLUB'), ('MEDIA CLUB', 'MEDIA CLUB'), ('AI CLUB', 'AI CLUB'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=50),
        ),
    ]
