# Generated by Django 4.2 on 2023-04-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_heldevent_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedevent',
            name='is_held',
            field=models.BooleanField(default=False),
        ),
    ]
