# Generated by Django 4.2 on 2023-04-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_publishedevent_is_held'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heldevent',
            name='number_of_attendees',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
