# Generated by Django 4.2 on 2023-04-22 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0009_alter_heldevent_number_of_attendees'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together={('user', 'held_event')},
        ),
    ]
